
project_id = "jednyqvexkcrwxubxici"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.performance-monitor]
verify_jwt = false
